export default {
  card: {
    padding: "15px",
    border: "1px solid rgba(255,255,255,.3)",
    borderRadius: 10,
    width: "100%",
    backgroundColor: "rgba(0,0,0,.3)",
  },
  text: {
    fontSize: "1rem",
    margin: "7px 0",
  },
  form: {
    width: "100%",
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  btn: {
    alignSelf: "flex-end",
    borderRadius: "50%",
    outline: "none",
    border: "none",
    marginLeft: 15,
    marginTop: 15,
    backgroundColor: "#396afc",
    color: "#fff",
    transition: "all 0.3s ease",
    "& svg": {
      border: "none",
      cursor: "pointer",
      textTransform: "uppercase",
      backgroundColor: "#396afc",
    },
    "&:hover": {
      transform: "translateX(-3px)",
      backgroundColor: "#2c60fd",
    },
  },
  deleteBtn: {
    color: "#fff",
    backgroundColor: "#d81b60",
    transition: "all 0.3s ease",
    "&:hover": {
      transform: "translateX(-3px)",
      backgroundColor: "#971243",
    },
  },
  personHeaderWrapper: {
    display: "flex",
    justifyContent: "space-between",
    alignContent: "center",
    flexDirection: "row",
  },
  editInput: {
    width: "100%",
    backgroundColor: "transparent",
    borderRadius: 0,
    border: "none",
    borderBottom: "2px solid rgba(255,255,255,.7)",
    color: "aliceblue",
    padding: "7px 0",
    fontSize: "1rem",
    "&:focus": {
      outline: "none",
      borderBottom: "2px solid #ffffff",
    },
  },
};
