export default {
  card: {
    padding: "15px",
    border: "1px solid rgba(255,255,255,.3)",
    borderRadius: 10,
    width: "100%",
    backgroundColor: "rgba(0,0,0,.3)",
  },
  text: {
    fontSize: "1rem",
    margin: "7px 0",
  },
  form: {
    width: "100%",
    marginTop: "30px",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  btn: {
    padding: "9px 20px",
    fontSize: "0.7rem",
    fontWeight: 500,
    border: "none",
    borderRadius: 7,
    cursor: "pointer",
    textTransform: "uppercase",
    outline: "none",
    backgroundColor: "#396afc",
    color: "aliceblue",
    minWidth: "20%",
    marginLeft: 15,
    marginTop: 15,
    alignSelf: "flex-end",
    transition: "all 0.3s ease",
    "&:hover": {
      transform: "translateX(-3px)",
      backgroundColor: "#2c60fd",
    },
  },
  editInput: {
    width: "100%",
    backgroundColor: "transparent",
    borderRadius: 0,
    border: "none",
    borderBottom: "2px solid rgba(255,255,255,.7)",
    color: "aliceblue",
    padding: "7px 0",
    fontSize: "1rem",
    "&:focus": {
      outline: "none",
      borderBottom: "2px solid #ffffff",
    },
  },
};
